global:
  scrape_interval: 5s

scrape_configs:
  - job_name: document-api
    static_configs:
      - targets: ["backend:8000"]

  - job_name: document-worker
    static_configs:
      - targets: ["worker:9101"]
